# Default configuration for Zerodha MCP

api:
  # Zerodha API configuration
  base_url: "https://api.kite.trade"
  timeout: 5  # seconds
  retry_attempts: 3

trading:
  # Trading parameters
  default_quantity: 1
  max_position_size: 100000  # in rupees
  stop_loss_percent: 2.0
  target_profit_percent: 4.0
  
risk_management:
  max_daily_loss: 10000  # in rupees
  max_trades_per_day: 10
  cooldown_period: 300  # seconds after a loss

strategies:
  default:
    timeframe: "5min"
    indicators:
      - type: "moving_average"
        period: 20
      - type: "rsi"
        period: 14
        overbought: 70
        oversold: 30

logging:
  level: "INFO"
  file: "mcp.log"
  max_size: 10485760  # 10MB
  backup_count: 5

llm:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 150 